sb1=input("Enter the Subject 1 :\n")
sb2=input("Enter the Subject 2 :\n")
sb3=input("Enter the Subject 3 :\n")
sb4=input("Enter the Subject 4 :\n")
sb5=input("Enter the Subject 5 :\n")
sm1=float(input("Enter the Mark of "+sb1+":\n"))
sm2=float(input("Enter the Mark of "+sb2+":\n"))
sm3=float(input("Enter the Mark of "+sb3+"\n"))
sm4=float(input("Enter the Mark of "+sb4+":\n"))
sm5=float(input("Enter the Mark of "+sb5+":\n"))
tl=sm1+sm2+sm3+sm4+sm5
print("Total Mark= ",tl,"\n Percentage = ",tl/500*100)
